### ISSUE TITLE
all liquidctl command except "liquidctl list" doesn't work in my computer

### ISSUE THREAD

**Issue by JeongJae0815** [liquidctl/liquidctl#245]
Hi
Thanks for every support about this water cooling control system. 👍 
I recently install liquidctl, but only list command works in my computer.
I really don't know why this kind of things happened.

![스크린샷 2020-12-24 오전 12 56 51](https://user-images.githubusercontent.com/22664723/103014914-e978b880-4582-11eb-8ad4-674591904681.png)

![스크린샷 2020-12-24 오전 12 57 18](https://user-images.githubusercontent.com/22664723/103014971-f9909800-4582-11eb-9122-73733850e689.png)

![스크린샷 2020-12-24 오전 12 57 30](https://user-images.githubusercontent.com/22664723/103014986-00b7a600-4583-11eb-9600-e360c5c11f1e.png)

```
   bionic_1.1.3   /  liquidctl status --debug
[DEBUG] liquidctl.cli: running liquidctl v1.4.2
[DEBUG] liquidctl.driver.usb: searching HidapiBus (api=hidraw, drivers=[CorsairHidPsu, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _CommonSmartDeviceDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 046d:101b
[DEBUG] liquidctl.driver.usb: probing drivers for device 046d:101b
[DEBUG] liquidctl.driver.usb: probing drivers for device 046d:101b
[DEBUG] liquidctl.driver.usb: probing drivers for device 046d:4002
[DEBUG] liquidctl.driver.usb: probing drivers for device 046d:405b
[DEBUG] liquidctl.driver.usb: probing drivers for device 046d:c52b
[DEBUG] liquidctl.driver.usb: searching PyUsbBus (drivers=[Hydro690Lc, Legacy690Lc, Modern690Lc, _CommonAsetekDriver])
[DEBUG] liquidctl.driver.usb: probing drivers for device 8087:8002
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0002
[DEBUG] liquidctl.driver.usb: probing drivers for device 8087:800a
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0002
[DEBUG] liquidctl.driver.usb: probing drivers for device 174c:3074
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0003
[DEBUG] liquidctl.driver.usb: probing drivers for device 174c:2074
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0608
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c09
[DEBUG] liquidctl.driver.usb: instanced driver for Corsair Hydro H100i v2
[DEBUG] liquidctl.driver.usb: probing drivers for device 1b1c:0c09
[DEBUG] liquidctl.driver.usb: instanced driver for Corsair Hydro H100i v2
[DEBUG] liquidctl.driver.usb: probing drivers for device 05e3:0608
[DEBUG] liquidctl.driver.usb: probing drivers for device 046d:c52b
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0002
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0003
[DEBUG] liquidctl.driver.usb: probing drivers for device 1d6b:0002
[DEBUG] liquidctl.cli: device: Corsair Hydro H100i v2
[DEBUG] liquidctl.driver.usb: setting the (first) configuration
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/liquidctl/driver/usb.py", line 241, in open
    cfg = self.usbdev.get_active_configuration()
  File "/usr/lib/python3/dist-packages/usb/core.py", line 875, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 236, in get_active_configuration
    self.managed_open()
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/liquidctl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/liquidctl/cli.py", line 297, in main
    dev.connect(**opts)
  File "/usr/local/lib/python3.6/dist-packages/liquidctl/driver/asetek.py", line 145, in connect
    super().connect(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/liquidctl/driver/usb.py", line 115, in connect
    self.device.open()
  File "/usr/local/lib/python3.6/dist-packages/liquidctl/driver/usb.py", line 244, in open
    self.usbdev.set_configuration()  # assume the first configuration
  File "/usr/lib/python3/dist-packages/usb/core.py", line 869, in set_configuration
    self._ctx.managed_set_configuration(self, configuration)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 147, in managed_set_configuration
    self.managed_open()
  File "/usr/lib/python3/dist-packages/usb/core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/usb/core.py", line 120, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 786, in open_device
    return _DeviceHandle(dev)
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 643, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "/usr/lib/python3/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 19] No such device (it may have been disconnected)
```

**Comment by jonasmalacofilho** [comment]
Starting with the first error:

```
UnicodeEncodeError: 'ascii' codec can't [...]
```

`liquidctl` cannot be executed under `LC_ALL=C` and Python 3.6, because non-ASCII characters are used in the output (see #84).

Also consider that `LC_ALL=C` is not really supposed to be used indiscriminately/globally:

> Using LC_ALL is strongly discouraged as it overrides everything. Please use it only when testing and never set it in a startup file. 
> _[Locale - Debian Wiki](https://wiki.debian.org/Locale)_

---

The second error is utterly unexpected.  Can you run

```
PYUSB_DEBUG=debug LIBUSB_DEBUG=4 liquidctl status --debug
```

to gather more information and show me the output?

**Comment by jonasmalacofilho** [comment]
Additionally, do you really have *two* H100i v2 coolers on that system?

**Comment by MarshallAsch** [comment]
It also did not seem to have been run as root, did you also install  the `udev` rules to allow non root access? Could this be an odd permissions error?

**Comment by jonasmalacofilho** [comment]
@MarshallAsch

That's possible... and it would make sense.

**Comment by JeongJae0815** [comment]
@jonasmalacofilho @MarshallAsch 
 I really appreciate you responding quickly.


> Starting with the first error:
> 
> ```
> UnicodeEncodeError: 'ascii' codec can't [...]
> ```
> 
> `liquidctl` cannot be executed under `LC_ALL=C` and Python 3.6, because non-ASCII characters are used in the output (see #84).
> 
> Also consider that `LC_ALL=C` is not really supposed to be used indiscriminately/globally:
> 
> > Using LC_ALL is strongly discouraged as it overrides everything. Please use it only when testing and never set it in a startup file.
> > _[Locale - Debian Wiki](https://wiki.debian.org/Locale)_
> 
> The second error is utterly unexpected. Can you run
> 
> ```
> PYUSB_DEBUG=debug LIBUSB_DEBUG=4 liquidctl status --debug
> ```
> 
> to gather more information and show me the output?
I can recognize my system's python version is lower than 3.6

**Comment by jonasmalacofilho** [comment]
> I recognized my system's python version is lower than 3.6.(default python version in ubuntu16.04 is lower than 3.6),

Oh... I only noticed that the first screenshot showed Python 3.6 paths but, indeed, the later dumps don't specify it (and Ubuntu 16.04 is quite old by now).

> Since I've installed liquidctl outside of docker, everything does work well.

Good to know! : )

I'll close this then...
