### ISSUE TITLE
Response does not match command for commander core

### ISSUE THREAD

**Issue by wildewouter** [liquidctl/liquidctl#490]
I've installed an iCue H150i Elite Capellix with Commander Core into my system which already included a Commander Pro. I dual boot Windows and Fedora (36). In Linux I control my fan speeds using liquidctl. When I run `status`, I get an error that the Commander Core throws an unexpected error: 

```
[ERROR] (cli) (log): unexpected error with Corsair Commander Core (experimental): AssertionError('response does not match command')
```

In debug, I can see the device is recognized:

```
[DEBUG] (usb) (probe): CommanderCore identified: Corsair Commander Core (experimental)
...
[DEBUG] (cli) (main): device: Corsair Commander Core (experimental)
...
[INFO] (cli) (log): detailed error: unexpected error with Corsair Commander Core (experimental): AssertionError('response does not match command')
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 212, in _wake_device_context
    yield
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 120, in set_fixed_speed
    res = self._read_data(_MODE_HW_SPEED_MODE, _DATA_TYPE_HW_SPEED_MODE)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 176, in _read_data
    self._send_command(_CMD_RESET)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 205, in _send_command
    assert buf[1] == command[0], 'response does not match command'
AssertionError: response does not match command

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/liquidctl/cli.py", line 468, in main
    _device_set_speed(dev, args, **opts)
  File "/usr/lib/python3.10/site-packages/liquidctl/cli.py", line 288, in _device_set_speed
    dev.set_fixed_speed(args['<channel>'].lower(), int(args['<percentage>'][0]), **opts)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 118, in set_fixed_speed
    with self._wake_device_context():
  File "/usr/lib64/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 214, in _wake_device_context
    self._send_command(_CMD_SLEEP)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 205, in _send_command
    assert buf[1] == command[0], 'response does not match command'
AssertionError: response does not match command
```

Is there somtehing I'm doing wrong? I did update the cooler to the latest version in Windows so maybe firmware too new?

`sudo liquidctl status`

Complete output:
```
$  sudo liquidctl status --debug
[DEBUG] (cli) (main): liquidctl: 1.10.0
[DEBUG] (cli) (main): platform: Linux-5.18.15-200.fc36.x86_64-x86_64-with-glibc2.35
[DEBUG] (cli) (_log_requirements): python: 3.10.5 (main, Jun  9 2022, 00:00:00) [GCC 12.1.1 20220507 (Red Hat 12.1.1-1)]
[DEBUG] (cli) (_log_requirements): colorlog: 6.5.0
[DEBUG] (cli) (_log_requirements): docopt: 0.6.2
[DEBUG] (cli) (_log_requirements): hidapi: 0.11.0.post2
[DEBUG] (cli) (_log_requirements): pyusb: 1.2.1
[DEBUG] (cli) (_log_requirements): smbus: 1.1
[DEBUG] (cli) (_log_requirements): libusb-package: version n/a (No package metadata was found for libusb-package)
[DEBUG] (smbus) (find_devices): searching LinuxI2c
[DEBUG] (smbus) (find_devices): LinuxI2c drivers: Ddr4Temperature, EvgaPascal, RogTuring, VengeanceRgb
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-3
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-10
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-1
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-8
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-6
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-4
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-11
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-2
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-0
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-9
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-7
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-5
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1532:006c (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 046d:0aaf (usage_page=0xff43 usage=0x0701)
[DEBUG] (usb) (find_devices): HID device: 046d:0aaf (usage_page=0xff43 usage=0x0702)
[DEBUG] (usb) (find_devices): HID device: 046d:0aaf (usage_page=0xff43 usage=0x0704)
[DEBUG] (usb) (find_devices): HID device: 046d:0aaf (usage_page=0xffff usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1462:7c37 (usage_page=0x0001 usage=0x0000)
[DEBUG] (usb) (find_devices): HID device: 1462:7c37 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c1c (usage_page=0xff42 usage=0x0001)
[DEBUG] (usb) (probe): CommanderCore identified: Corsair Commander Core (experimental)
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c1c (usage_page=0xff42 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c10 (usage_page=0x0084 usage=0x0052)
[DEBUG] (usb) (__init__): has kernel driver: corsair_cpro (/sys/class/hidraw/hidraw10/device/hwmon/hwmon4)
[DEBUG] (usb) (probe): CommanderPro identified: Corsair Commander Pro
[DEBUG] (usb) (find_devices): HID device: 04d9:0169 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 04d9:0169 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 04d9:0169 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xffc0 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xffc0 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xffc0 usage=0x0014)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x0022)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x000a)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x000c)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0x0001 usage=0x003a)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0xff00 usage=0x000c)
[DEBUG] (usb) (find_devices): HID device: 1532:0528 (usage_page=0x0001 usage=0x003a)
[DEBUG] (usb) (find_devices): HID device: 0451:82ff (usage_page=0xffb0 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:0893 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (find_devices): USB device: 0781:5583
[DEBUG] (usb) (find_devices): USB device: 0451:8440
[DEBUG] (usb) (find_devices): USB device: 046d:0893
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 0451:82ee
[DEBUG] (usb) (find_devices): USB device: 0451:82ff
[DEBUG] (usb) (find_devices): USB device: 1532:0528
[DEBUG] (usb) (find_devices): USB device: 045e:02ea
[DEBUG] (usb) (find_devices): USB device: 04d9:0169
[DEBUG] (usb) (find_devices): USB device: 0451:8442
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 05e3:0610
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c10
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c1c
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 1462:7c37
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 8087:0aa7
[DEBUG] (usb) (find_devices): USB device: 046d:0aaf
[DEBUG] (usb) (find_devices): USB device: 1532:006c
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (cli) (main): device: Corsair Commander Core (experimental)
[DEBUG] (usb) (clear_enqueued_reports): discarded 0 previously enqueued reports
[DEBUG] (usb) (write): writting report 0x00 with 1024 bytes: 08:01:03:00:02:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (read): read 96 bytes: 00:01:00:02:0a:db:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (clear_enqueued_reports): discarded 9 previously enqueued reports
[DEBUG] (usb) (write): writting report 0x00 with 1024 bytes: 08:05:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (read): read 96 bytes: f0:00:00:02:0a:db:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (clear_enqueued_reports): discarded 10 previously enqueued reports
[DEBUG] (usb) (write): writting report 0x00 with 1024 bytes: 08:01:03:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (read): read 96 bytes: f0:00:00:02:0a:db:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[INFO] (cli) (log): detailed error: unexpected error with Corsair Commander Core (experimental): AssertionError('response does not match command')
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 212, in _wake_device_context
    yield
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 97, in get_status
    for i, speed in enumerate(self._get_speeds()):
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 150, in _get_speeds
    res = self._read_data(_MODE_GET_SPEEDS, _DATA_TYPE_SPEEDS)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 176, in _read_data
    self._send_command(_CMD_RESET)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 205, in _send_command
    assert buf[1] == command[0], 'response does not match command'
AssertionError: response does not match command

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/liquidctl/cli.py", line 462, in main
    status = dev.get_status(**opts)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 96, in get_status
    with self._wake_device_context():
  File "/usr/lib64/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 214, in _wake_device_context
    self._send_command(_CMD_SLEEP)
  File "/usr/lib/python3.10/site-packages/liquidctl/driver/commander_core.py", line 205, in _send_command
    assert buf[1] == command[0], 'response does not match command'
AssertionError: response does not match command
[ERROR] (cli) (log): unexpected error with Corsair Commander Core (experimental): AssertionError('response does not match command')
[DEBUG] (cli) (main): device: Corsair Commander Pro
[DEBUG] (keyval) (__init__): data in /var/run/liquidctl/vid1b1c_pid0c10/loc10
[INFO] (commander_pro) (get_status): bound to corsair_cpro kernel driver, reading status from hwmon
[DEBUG] (keyval) (load): loaded temp_sensors_connected=[0, 0, 0, 0] (from /var/run/liquidctl/vid1b1c_pid0c10/loc10/temp_sensors_connected)
[DEBUG] (keyval) (load): loaded fan_modes=[2, 2, 2, 2, 2, 2] (from /var/run/liquidctl/vid1b1c_pid0c10/loc10/fan_modes)
[DEBUG] (hwmon) (get_string): read fan1_input: 767
[DEBUG] (hwmon) (get_string): read fan2_input: 787
[DEBUG] (hwmon) (get_string): read fan3_input: 772
[DEBUG] (hwmon) (get_string): read fan4_input: 998
[DEBUG] (hwmon) (get_string): read fan5_input: 972
[DEBUG] (hwmon) (get_string): read fan6_input: 793
[DEBUG] (hwmon) (get_string): read in0_input: 11949
[DEBUG] (hwmon) (get_string): read in1_input: 4959
[DEBUG] (hwmon) (get_string): read in2_input: 3322
Corsair Commander Pro
├── Fan 1 speed      767  rpm
├── Fan 2 speed      787  rpm
├── Fan 3 speed      772  rpm
├── Fan 4 speed      998  rpm
├── Fan 5 speed      972  rpm
├── Fan 6 speed      793  rpm
├── +12V rail      11.95  V
├── +5V rail        4.96  V
└── +3.3V rail      3.32  V
```

---

Additional information about the system:

- Affected device(s): 
- Operating system and version: Fedora 36
- Liquidctl installation method: `dnf`
- Output of `liquidctl --version`: `liquidctl v1.10.0 (Linux-5.18.15-200.fc36.x86_64-x86_64-with-glibc2.35)`

**Comment by jonasmalacofilho** [comment]
We have an open issue for this bug: #464.  I'm going to close this one to keep all discussion in a single place.

**Comment by wildewouter** [comment]
Thanks
