### ISSUE TITLE
[Win][CommanderXT] Status command errors when iCUE is running

### ISSUE THREAD

**Issue by Myaanee** [liquidctl/liquidctl#581]
### Describe the bug

When iCue is running and I try to access the status of my Commander XT i get the following error:
`[ERROR] (cli) (log): Corsair Commander Core XT (experimental): unexpected error: AssertionError('response does not match command')`

### Commands executed

> liquidctl status --debug

### Output of all relevant commands with `--debug` flag

<details><summary>Click to show console output</summary>

<p>

```
>liquidctl status --debug
[DEBUG] (cli) (_log_env_infos): script: C:\Python310\Scripts\liquidctl
[DEBUG] (cli) (_log_env_infos): version: 1.12.1
[DEBUG] (cli) (_log_env_infos): platform: Windows-10-10.0.22621-SP0
[DEBUG] (cli) (_log_env_infos): python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
[DEBUG] (cli) (_log_env_infos): encoding: cp1252 default, cp1252 preferred, utf8_mode 0
[DEBUG] (cli) (_log_env_infos): with colorlog: 6.7.0
[DEBUG] (cli) (_log_env_infos): with crcmod: 1.7
[DEBUG] (cli) (_log_env_infos): with docopt: 0.6.2
[DEBUG] (cli) (_log_env_infos): with hidapi: 0.13.1
[DEBUG] (cli) (_log_env_infos): with pyusb: 1.2.1
[DEBUG] (cli) (_log_env_infos): with pillow: 9.4.0
[DEBUG] (cli) (_log_env_infos): with smbus: version n/a (No package metadata was found for smbus)
[DEBUG] (cli) (_log_env_infos): with winusbcdc: 1.5
[DEBUG] (cli) (_log_env_infos): with libusb-package: 1.0.26.1
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: Aquacomputer, AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 1b1c:1bf0 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 03f0:0294 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1b2d (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c2a (usage_page=0xff42 usage=0x0001)
[DEBUG] (usb) (probe): CommanderCore identified: Corsair Commander Core XT (experimental)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1bf0 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1b2d (usage_page=0xffc2 usage=0x0003)
[DEBUG] (usb) (find_devices): HID device: 03f0:028c (usage_page=0xff90 usage=0xff00)
[DEBUG] (usb) (find_devices): HID device: 043e:9a39 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c547 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 046d:c547 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1b2d (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 048d:8297 (usage_page=0xff89 usage=0x0010)
[DEBUG] (usb) (find_devices): HID device: 1b1c:0c2a (usage_page=0xff42 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 046d:c547 (usage_page=0xff00 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 03f0:028c (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1b2d (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1bf0 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 03f0:028c (usage_page=0xffff usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1bf0 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 046d:c547 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1b2d (usage_page=0xffc0 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 048d:8297 (usage_page=0xff89 usage=0x00cc)
[DEBUG] (usb) (probe): RgbFusion2 identified: Gigabyte RGB Fusion 2.0 8297 Controller
[DEBUG] (usb) (find_devices): HID device: 046d:c232 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1bf0 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c547 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c547 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 0bda:1100 (usage_page=0xffda usage=0x00da)
[DEBUG] (usb) (find_devices): HID device: 1b1c:1b2d (usage_page=0xffc2 usage=0x0004)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (enumerate): using libusb_package.find
[DEBUG] (usb) (find_devices): USB device: 1022:149c
[DEBUG] (usb) (find_devices): USB device: 1b1c:1b2d
[DEBUG] (usb) (find_devices): USB device: 048d:8297
[DEBUG] (usb) (find_devices): USB device: 046d:c547
[DEBUG] (usb) (find_devices): USB device: 0bda:1100
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (usb) (find_devices): USB device: 174c:3074
[DEBUG] (usb) (find_devices): USB device: 214b:7250
[DEBUG] (usb) (find_devices): USB device: 174c:55aa
[DEBUG] (usb) (find_devices): USB device: 1022:149c
[DEBUG] (usb) (find_devices): USB device: 0bda:0411
[DEBUG] (usb) (find_devices): USB device: 0bda:0411
[DEBUG] (usb) (find_devices): USB device: 03f0:0294
[DEBUG] (usb) (find_devices): USB device: 0bda:5411
[DEBUG] (usb) (find_devices): USB device: 0bda:5411
[DEBUG] (usb) (find_devices): USB device: 1b1c:1c00
[DEBUG] (usb) (find_devices): USB device: 0bda:5418
[DEBUG] (usb) (find_devices): USB device: 174c:55aa
[DEBUG] (usb) (find_devices): USB device: 174c:2074
[DEBUG] (usb) (find_devices): USB device: 043e:9a39
[DEBUG] (usb) (find_devices): USB device: 03f0:028c
[DEBUG] (usb) (find_devices): USB device: 1b1c:0c2a
[DEBUG] (usb) (find_devices): USB device: 1022:149c
[DEBUG] (usb) (find_devices): USB device: 04f3:0c3d
[DEBUG] (usb) (find_devices): USB device: 05e3:0608
[DEBUG] (cli) (main): device: Corsair Commander Core XT (experimental)
[DEBUG] (usb) (clear_enqueued_reports): discarded 0 previously enqueued reports
[DEBUG] (usb) (write): writing report 0x00 with 96 bytes: 08:01:03:00:02:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (write): wrote 385 total bytes, expected 97
[DEBUG] (usb) (read): read 96 bytes: 00:01:00:07:00:06:00:00:14:00:01:00:14:00:02:00:14:00:03:00:14:00:04:00:14:00:05:00:14:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (clear_enqueued_reports): discarded 0 previously enqueued reports
[DEBUG] (usb) (write): writing report 0x00 with 96 bytes: 08:0d:00:17:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (write): wrote 385 total bytes, expected 97
[DEBUG] (usb) (read): read 96 bytes: 00:0d:00:07:00:06:00:00:14:00:01:00:14:00:02:00:14:00:03:00:14:00:04:00:14:00:05:00:14:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (clear_enqueued_reports): discarded 3 previously enqueued reports
[DEBUG] (usb) (write): writing report 0x00 with 96 bytes: 08:08:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (write): wrote 385 total bytes, expected 97
[DEBUG] (usb) (read): read 96 bytes: 00:06:00:07:00:06:00:00:14:00:01:00:14:00:02:00:14:00:03:00:14:00:04:00:14:00:05:00:14:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (clear_enqueued_reports): discarded 1 previously enqueued reports
[DEBUG] (usb) (write): writing report 0x00 with 96 bytes: 08:01:03:00:01:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[DEBUG] (usb) (write): wrote 385 total bytes, expected 97
[DEBUG] (usb) (read): read 96 bytes: 00:07:00:07:00:06:00:00:14:00:01:00:14:00:02:00:14:00:03:00:14:00:04:00:14:00:05:00:14:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00:00
[INFO] (cli) (log): detailed error: Corsair Commander Core XT (experimental): unexpected error: AssertionError('response does not match command')
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 241, in _wake_device_context
    yield
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 115, in get_status
    for i, speed in enumerate(self._get_speeds()):
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 177, in _get_speeds
    res = self._read_data(_MODE_GET_SPEEDS, _DATA_TYPE_SPEEDS)
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 204, in _read_data
    raw_data = self._send_command(_CMD_READ)
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 234, in _send_command
    assert buf[1] == command[0], 'response does not match command'
AssertionError: response does not match command

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\liquidctl\cli.py", line 469, in main
    status = dev.get_status(**opts)
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 114, in get_status
    with self._wake_device_context():
  File "C:\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 243, in _wake_device_context
    self._send_command(_CMD_SLEEP)
  File "C:\Python310\lib\site-packages\liquidctl\driver\commander_core.py", line 234, in _send_command
    assert buf[1] == command[0], 'response does not match command'
AssertionError: response does not match command
[ERROR] (cli) (log): Corsair Commander Core XT (experimental): unexpected error: AssertionError('response does not match command')
[DEBUG] (cli) (main): device: Gigabyte RGB Fusion 2.0 8297 Controller
[INFO] (rgb_fusion2) (get_status): status reports not available from Gigabyte RGB Fusion 2.0 8297 Controller

C:\Windows\System32>

```
</p>

</details>

### Affected device

Corsair Commander Core XT 

### Operating system and version

Windows 11

### Installation method

pip

### Version of liquidctl

liquidctl v1.12.1 (Windows-10-10.0.22621-SP0)

**Comment by jonasmalacofilho** [comment]
Because of some peculiarities in the protocol, running alongside iCue probably isn't something we can support for that device.

Are you aware if any other (preferably open-source) software manages to read the status information from that device when iCue (or its background service) is simultaneously running?
