### ISSUE TITLE
Request: NZXT HUE+ RGB Controller

### ISSUE THREAD

**Issue by eduncan911** [liquidctl/liquidctl#717]
### Device type

RGB LED Controller

### Product page

https://www.bhphotovideo.com/c/product/1266788-REG/nzxt_ac_hueps_m1_hue_advanced_pc_lighting.html

### First-party software

NZXT CAM

### What configuration functionality does the device support?

lighting of accessories like RGB fans or LED strips

### Physical connection

USB Header

### Connection protocol

USB

### Additional information about the device

```
$ lsusb -d 04d8:00df
Bus 001 Device 002: ID 04d8:00df Microchip Technology, Inc. MCP2200 USB Serial Port Emulator

$ liquidctl list
Device #0: Corsair CMD16GX4M4B3600C18 DIMM1
Device #1: Corsair CMD16GX4M4B3600C18 DIMM2
Device #2: Corsair CMD16GX4M4B3600C18 DIMM3
Device #3: Corsair CMD16GX4M4B3600C18 DIMM4

(bonus points on how to RGB the DIMMs)

$ liquidctl status --unsafe=smbus,ddr4_temperature --debug
[DEBUG] (cli) (_log_env_infos): script: /usr/local/bin/liquidctl
[DEBUG] (cli) (_log_env_infos): version: 1.13.0
[DEBUG] (cli) (_log_env_infos): platform: Linux-6.8.0-76060800daily20240311-generic-x86_64-with-glibc2.35
[DEBUG] (cli) (_log_env_infos): python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
[DEBUG] (cli) (_log_env_infos): encoding: UTF-8 current, UTF-8 preferred, utf8_mode 0
[DEBUG] (cli) (_log_env_infos): with colorlog: 6.8.2
[DEBUG] (cli) (_log_env_infos): with crcmod: 1.7
[DEBUG] (cli) (_log_env_infos): with docopt: 0.6.2
[DEBUG] (cli) (_log_env_infos): with hidapi: 0.9.0.post3
[DEBUG] (cli) (_log_env_infos): with pyusb: 1.2.1.post1
[DEBUG] (cli) (_log_env_infos): with pillow: 9.0.1
[DEBUG] (cli) (_log_env_infos): with smbus: 1.1.post2
[DEBUG] (cli) (_log_env_infos): with winusbcdc: version n/a (No package metadata was found for winusbcdc)
[DEBUG] (cli) (_log_env_infos): with libusb-package: version n/a (No package metadata was found for libusb-package)
[DEBUG] (smbus) (find_devices): searching LinuxI2c
[DEBUG] (smbus) (find_devices): LinuxI2c drivers: Ddr4Temperature, EvgaPascal, RogTuring, VengeanceRgb
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0052 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-3
[DEBUG] (smbus) (find_devices): I²C adapter: 0-001b (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0050 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-1
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0019 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0037 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-6
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0053 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-4
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0051 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-2
[DEBUG] (smbus) (find_devices): I²C adapter: 0-001a (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-0
[DEBUG] (ddr4) (probe): Ddr4Temperature identified: Corsair CMD16GX4M4B3600C18 DIMM1
[DEBUG] (ddr4) (probe): Ddr4Temperature identified: Corsair CMD16GX4M4B3600C18 DIMM2
[DEBUG] (ddr4) (probe): Ddr4Temperature identified: Corsair CMD16GX4M4B3600C18 DIMM3
[DEBUG] (ddr4) (probe): Ddr4Temperature identified: Corsair CMD16GX4M4B3600C18 DIMM4
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-7
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0018 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: 0-0036 (skipped, not a bus or unsupported adapter)
[DEBUG] (smbus) (find_devices): I²C adapter: i2c-5
[DEBUG] (usb) (find_devices): searching HidapiBus
[DEBUG] (usb) (find_devices): HidapiBus drivers: Aquacomputer, AuraLed, CommanderCore, CommanderPro, CorsairHidPsu, H1V2, HydroPlatinum, Kraken2, KrakenX3, KrakenZ3, NzxtEPsu, RgbFusion2, SmartDevice, SmartDevice2, _BaseSmartDevice
[DEBUG] (usb) (find_devices): HID device: 046d:c548 (usage_page=0x0001 usage=0x0006)
[DEBUG] (usb) (find_devices): HID device: 046d:c548 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 046d:c548 (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c548 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c548 (usage_page=0x0001 usage=0x0080)
[DEBUG] (usb) (find_devices): HID device: 046d:c548 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c548 (usage_page=0xff00 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 046d:c52f (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 046d:c52f (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:4094 (usage_page=0x0001 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 046d:4094 (usage_page=0x0001 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:4094 (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:4094 (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:4094 (usage_page=0xff00 usage=0x0002)
[DEBUG] (usb) (find_devices): HID device: 046d:4094 (usage_page=0xff00 usage=0x0004)
[DEBUG] (usb) (find_devices): HID device: 046d:c52f (usage_page=0x000c usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c52f (usage_page=0xff00 usage=0x0001)
[DEBUG] (usb) (find_devices): HID device: 046d:c52f (usage_page=0xff00 usage=0x0002)
[DEBUG] (usb) (find_devices): searching PyUsbBus
[DEBUG] (usb) (find_devices): PyUsbBus drivers: Hydro690Lc, HydroPro, Legacy690Lc, Modern690Lc, _Base690Lc, _ModernBase690Lc
[DEBUG] (usb) (find_devices): USB device: 1d6b:0003
[DEBUG] (usb) (find_devices): USB device: 046d:c52f
[DEBUG] (usb) (find_devices): USB device: 046d:c548
[DEBUG] (usb) (find_devices): USB device: 0b05:17cb
[DEBUG] (usb) (find_devices): USB device: 04d8:00df
[DEBUG] (usb) (find_devices): USB device: 1d6b:0002
[DEBUG] (cli) (main): device: Corsair CMD16GX4M4B3600C18 DIMM1
[INFO] (cli) (log): detailed error: Corsair CMD16GX4M4B3600C18 DIMM1: unexpected OS error: OSError(16, 'Device or resource busy')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/cli.py", line 469, in main
    status = dev.get_status(**opts)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 217, in get_status
    treg = self._read_temperature_register()
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 242, in _read_temperature_register
    treg = self._smbus.read_word_data(self._ts_address, self._REG_TEMPERATURE)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/smbus.py", line 124, in read_word_data
    value = self._smbus.read_word_data(address, register)
OSError: [Errno 16] Device or resource busy
[ERROR] (cli) (log): Corsair CMD16GX4M4B3600C18 DIMM1: unexpected OS error: OSError(16, 'Device or resource busy')
[DEBUG] (cli) (main): device: Corsair CMD16GX4M4B3600C18 DIMM2
[INFO] (cli) (log): detailed error: Corsair CMD16GX4M4B3600C18 DIMM2: unexpected OS error: OSError(16, 'Device or resource busy')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/cli.py", line 469, in main
    status = dev.get_status(**opts)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 217, in get_status
    treg = self._read_temperature_register()
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 242, in _read_temperature_register
    treg = self._smbus.read_word_data(self._ts_address, self._REG_TEMPERATURE)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/smbus.py", line 124, in read_word_data
    value = self._smbus.read_word_data(address, register)
OSError: [Errno 16] Device or resource busy
[ERROR] (cli) (log): Corsair CMD16GX4M4B3600C18 DIMM2: unexpected OS error: OSError(16, 'Device or resource busy')
[DEBUG] (cli) (main): device: Corsair CMD16GX4M4B3600C18 DIMM3
[INFO] (cli) (log): detailed error: Corsair CMD16GX4M4B3600C18 DIMM3: unexpected OS error: OSError(16, 'Device or resource busy')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/cli.py", line 469, in main
    status = dev.get_status(**opts)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 217, in get_status
    treg = self._read_temperature_register()
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 242, in _read_temperature_register
    treg = self._smbus.read_word_data(self._ts_address, self._REG_TEMPERATURE)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/smbus.py", line 124, in read_word_data
    value = self._smbus.read_word_data(address, register)
OSError: [Errno 16] Device or resource busy
[ERROR] (cli) (log): Corsair CMD16GX4M4B3600C18 DIMM3: unexpected OS error: OSError(16, 'Device or resource busy')
[DEBUG] (cli) (main): device: Corsair CMD16GX4M4B3600C18 DIMM4
[INFO] (cli) (log): detailed error: Corsair CMD16GX4M4B3600C18 DIMM4: unexpected OS error: OSError(16, 'Device or resource busy')
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/cli.py", line 469, in main
    status = dev.get_status(**opts)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 217, in get_status
    treg = self._read_temperature_register()
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/ddr4.py", line 242, in _read_temperature_register
    treg = self._smbus.read_word_data(self._ts_address, self._REG_TEMPERATURE)
  File "/usr/local/lib/python3.10/dist-packages/liquidctl/driver/smbus.py", line 124, in read_word_data
    value = self._smbus.read_word_data(address, register)
OSError: [Errno 16] Device or resource busy
[ERROR] (cli) (log): Corsair CMD16GX4M4B3600C18 DIMM4: unexpected OS error: OSError(16, 'Device or resource busy')
```

### Can you help with implementing or testing the changes needed for liquidctl to support this device?

testing changes on Linux, implementing the changes

**Comment by eduncan911** [comment]
This seems to be a device that was briefly sold and quickly replaced within a few months with the HUE 2 device.  So it's kind of rare.  But, I have one.  

Technically, the device's model number on the device is: `AC-HUEPS-M1`

Odd how it shows up as a simple serial emulator.

**Comment by jonasmalacofilho** [comment]
While it's not something I'd be willing to work on myself, if you can send a PR (with some tests using a mock device), I'll gladly review it and (if everything is ok) merge it.

You can take a look at #24 for a previous technical discussion on how this could be implemented. That's a very old issue, and liquidctl has changed a bit since then, but I think most of it will still be useful.

Just a word of caution: the last person to try this bricked their device. Admittedly (from what I recall) they tried to send Smart Device commands to their HUE+ but, still, these HUE+ are a bit sensitive...

**Comment by eduncan911** [comment]
Thanks!  I will close this for now as a path forward with #24 if one is so inclined.
